# Generated by Django 4.2.5 on 2023-10-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eksamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dato", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Personale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Skole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="WishDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "censor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skoleapp.personale",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skoleapp.eksamen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skoleklasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=255)),
                (
                    "skole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skoleapp.skole"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="personale",
            name="skole",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skoleapp.skole"
            ),
        ),
        migrations.AddField(
            model_name="eksamen",
            name="fag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skoleapp.fag"
            ),
        ),
        migrations.AddField(
            model_name="eksamen",
            name="skoleklasse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skoleapp.skoleklasse"
            ),
        ),
    ]
